{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 items\r\n",
      "-rwxrwxrwx   1 jovyan supergroup   76861985 2018-08-01 17:15 /data/wiki/en_articles_part/articles-part\r\n"
     ]
    }
   ],
   "source": [
    "! hdfs dfs -ls /data/wiki/en_articles_part"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting mapper.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile mapper.py\n",
    "\n",
    "import sys\n",
    "from line in sys.stdin:\n",
    "    words = line.split()\n",
    "for word in words:\n",
    "    print('{0}\\t{1}'.format(word,1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting reducer.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile reducer.py\n",
    "\n",
    "import sys\n",
    "\n",
    "curr_word = None\n",
    "curr_count = 0\n",
    "\n",
    "for line in sys.stdin:\n",
    "    word,count = line.split('\\t')\n",
    "    count = int(count)\n",
    "    if word == curr_word:\n",
    "        curr_count += count\n",
    "    else:\n",
    "        if curr_word:\n",
    "            print('{0}\\t{1}'.format(curr_word,curr_count))\n",
    "        curr_word = word\n",
    "        curr_count = count\n",
    "    if curr_word == word:\n",
    "        print('{0}\\t{1}'.format(curr_word,curr_count))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Writing wordcount.txt\n"
     ]
    }
   ],
   "source": [
    "%%writefile wordcount.txt\n",
    "\n",
    "hello how are you ?\n",
    "where are you ?\n",
    "what are you doing for a living ?\n",
    "what experience are you packing up in this lifetime ?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "mapper.py\t      supervisord.log\t       wordcount.txt\r\n",
      "README.md\t      supervisord.pid\t       WordsRatingTask1.ipynb\r\n",
      "reducer.py\t      WordCountResolved.ipynb\r\n",
      "StopWordsTask2.ipynb  WordCountTask0.ipynb\r\n"
     ]
    }
   ],
   "source": [
    "!ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -mkdir word/\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -chmod 777 word/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 items\r\n",
      "-rw-r--r--   1 jovyan supergroup        124 2019-03-08 06:33 word/wordcount.txt\r\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls word/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -put wordcount.txt word/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 3 items\r\n",
      "drwxr-xr-x   - root   supergroup          0 2018-08-01 17:15 /data\r\n",
      "drwxr-xr-x   - jovyan supergroup          0 2018-08-01 17:15 /datasets\r\n",
      "drwxr-xr-x   - root   supergroup          0 2017-10-17 13:11 /user\r\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls  /"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 items\r\n",
      "-rw-r--r--   1 jovyan supergroup        124 2019-03-08 06:33 word/wordcount.txt\r\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls word/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -chmod 777 word/wordcount.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 items\r\n",
      "-rwxrwxrwx   1 jovyan supergroup        124 2019-03-08 06:33 word/wordcount.txt\r\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls word/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -chmod 777 word"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 items\n",
      "-rwxrwxrwx   1 jovyan supergroup        124 2019-03-08 06:33 word/wordcount.txt\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls word"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "!hdfs dfs -mkdir outputWord"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -chmod 777 outputWord/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -ls outputWord"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "packageJobJar: [/tmp/hadoop-unjar5117510284629629139/] [] /tmp/streamjob513081076811918921.jar tmpDir=null\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "19/03/08 06:45:27 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:45:28 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:45:29 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 06:45:30 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:45:30 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 06:45:30 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0001\n",
      "19/03/08 06:45:31 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0001\n",
      "19/03/08 06:45:32 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0001/\n",
      "19/03/08 06:45:32 INFO mapreduce.Job: Running job: job_1552022483956_0001\n",
      "19/03/08 06:45:49 INFO mapreduce.Job: Job job_1552022483956_0001 running in uber mode : false\n",
      "19/03/08 06:45:49 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 06:46:04 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000003/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:04 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000002/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:18 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000004/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:19 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000005/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:33 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000007/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:34 INFO mapreduce.Job: Task Id : attempt_1552022483956_0001_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0001/container_1552022483956_0001_01_000008/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:46:48 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 06:46:49 INFO mapreduce.Job: Job job_1552022483956_0001 failed with state FAILED due to: Task failed task_1552022483956_0001_m_000001\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 06:46:49 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=1\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=99705\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=99705\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=99705\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=102097920\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 06:46:49 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n",
      "cat: `outputWord1/part-00000': No such file or directory\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "NUM_REDUCERS=1\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    -D mapred.jab.name=\"Streaming wordCount\" \\\n",
    "    -D mapreduce.job.reduces=${NUM_REDUCERS} \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output outputWord1\n",
    "\n",
    "hdfs dfs -cat outputWord1/part-00000 | head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 3 items\n",
      "drwxrwxrwx   - jovyan supergroup          0 2019-03-08 06:38 outputWord\n",
      "drwxr-xr-x   - jovyan supergroup          0 2019-03-08 06:46 outputWord1\n",
      "drwxrwxrwx   - jovyan supergroup          0 2019-03-08 06:33 word\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -ls outputWord1/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cat: `outputWord1/part-00000': No such file or directory\r\n"
     ]
    }
   ],
   "source": [
    "!hdfs dfs -cat outputWord1/part-00000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "!hdfs dfs -ls outputWord"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "rm: `wordcount_result_1552027939648199': No such file or directory\n",
      "19/03/08 06:52:30 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:52:30 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:52:32 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:52:32 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 06:52:32 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:52:32 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:52:32 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 06:52:33 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0002\n",
      "19/03/08 06:52:33 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0002\n",
      "19/03/08 06:52:33 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0002/\n",
      "19/03/08 06:52:33 INFO mapreduce.Job: Running job: job_1552022483956_0002\n",
      "19/03/08 06:52:50 INFO mapreduce.Job: Job job_1552022483956_0002 running in uber mode : false\n",
      "19/03/08 06:52:50 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 06:53:09 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000002/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:53:11 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000003/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:53:26 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000004/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:53:26 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000005/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:53:43 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000006/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:53:44 INFO mapreduce.Job: Task Id : attempt_1552022483956_0002_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0002/container_1552022483956_0002_01_000007/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:54:00 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 06:54:00 INFO mapreduce.Job: Job job_1552022483956_0002 failed with state FAILED due to: Task failed task_1552022483956_0002_m_000000\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 06:54:00 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=1\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=122984\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=122984\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=122984\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=125935616\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 06:54:00 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n",
      "cat: `wordcount_result_1552027939648199/part-00000': No such file or directory\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "OUT_DIR=\"wordcount_result_\"$(date +\"%s%6N\")\n",
    "NUM_REDUCERS=1\n",
    "\n",
    "hdfs dfs -rm -r -skipTrash ${OUT_DIR} > /dev/null\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    -D mapred.jab.name=\"Streaming wordCount\" \\\n",
    "    -D mapreduce.job.reduces=${NUM_REDUCERS} \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output ${OUT_DIR} > /dev/null\n",
    "\n",
    "hdfs dfs -cat ${OUT_DIR}/part-00000 | head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "packageJobJar: [/tmp/hadoop-unjar5705795374228583009/] [] /tmp/streamjob3123988543650772852.jar tmpDir=null\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "-rm: Not enough arguments: expected 1 but got 0\n",
      "Usage: hadoop fs [generic options]\n",
      "\t[-appendToFile <localsrc> ... <dst>]\n",
      "\t[-cat [-ignoreCrc] <src> ...]\n",
      "\t[-checksum <src> ...]\n",
      "\t[-chgrp [-R] GROUP PATH...]\n",
      "\t[-chmod [-R] <MODE[,MODE]... | OCTALMODE> PATH...]\n",
      "\t[-chown [-R] [OWNER][:[GROUP]] PATH...]\n",
      "\t[-copyFromLocal [-f] [-p] [-l] [-d] <localsrc> ... <dst>]\n",
      "\t[-copyToLocal [-f] [-p] [-ignoreCrc] [-crc] <src> ... <localdst>]\n",
      "\t[-count [-q] [-h] [-v] [-t [<storage type>]] [-u] [-x] <path> ...]\n",
      "\t[-cp [-f] [-p | -p[topax]] [-d] <src> ... <dst>]\n",
      "\t[-createSnapshot <snapshotDir> [<snapshotName>]]\n",
      "\t[-deleteSnapshot <snapshotDir> <snapshotName>]\n",
      "\t[-df [-h] [<path> ...]]\n",
      "\t[-du [-s] [-h] [-x] <path> ...]\n",
      "\t[-expunge]\n",
      "\t[-find <path> ... <expression> ...]\n",
      "\t[-get [-f] [-p] [-ignoreCrc] [-crc] <src> ... <localdst>]\n",
      "\t[-getfacl [-R] <path>]\n",
      "\t[-getfattr [-R] {-n name | -d} [-e en] <path>]\n",
      "\t[-getmerge [-nl] [-skip-empty-file] <src> <localdst>]\n",
      "\t[-help [cmd ...]]\n",
      "\t[-ls [-C] [-d] [-h] [-q] [-R] [-t] [-S] [-r] [-u] [<path> ...]]\n",
      "\t[-mkdir [-p] <path> ...]\n",
      "\t[-moveFromLocal <localsrc> ... <dst>]\n",
      "\t[-moveToLocal <src> <localdst>]\n",
      "\t[-mv <src> ... <dst>]\n",
      "\t[-put [-f] [-p] [-l] [-d] <localsrc> ... <dst>]\n",
      "\t[-renameSnapshot <snapshotDir> <oldName> <newName>]\n",
      "\t[-rm [-f] [-r|-R] [-skipTrash] [-safely] <src> ...]\n",
      "\t[-rmdir [--ignore-fail-on-non-empty] <dir> ...]\n",
      "\t[-setfacl [-R] [{-b|-k} {-m|-x <acl_spec>} <path>]|[--set <acl_spec> <path>]]\n",
      "\t[-setfattr {-n name [-v value] | -x name} <path>]\n",
      "\t[-setrep [-R] [-w] <rep> <path> ...]\n",
      "\t[-stat [format] <path> ...]\n",
      "\t[-tail [-f] <file>]\n",
      "\t[-test -[defsz] <path>]\n",
      "\t[-text [-ignoreCrc] <src> ...]\n",
      "\t[-touchz <path> ...]\n",
      "\t[-truncate [-w] <length> <path> ...]\n",
      "\t[-usage [cmd ...]]\n",
      "\n",
      "Generic options supported are\n",
      "-conf <configuration file>     specify an application configuration file\n",
      "-D <property=value>            use value for given property\n",
      "-fs <file:///|hdfs://namenode:port> specify default filesystem URL to use, overrides 'fs.defaultFS' property from configurations.\n",
      "-jt <local|resourcemanager:port>    specify a ResourceManager\n",
      "-files <comma separated list of files>    specify comma separated files to be copied to the map reduce cluster\n",
      "-libjars <comma separated list of jars>    specify comma separated jar files to include in the classpath.\n",
      "-archives <comma separated list of archives>    specify comma separated archives to be unarchived on the compute machines.\n",
      "\n",
      "The general command line syntax is\n",
      "command [genericOptions] [commandOptions]\n",
      "\n",
      "Usage: hadoop fs [generic options] -rm [-f] [-r|-R] [-skipTrash] [-safely] <src> ...\n",
      "19/03/08 06:55:42 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:55:42 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:55:44 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:55:44 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 06:55:44 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:55:44 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:55:44 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 06:55:45 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0003\n",
      "19/03/08 06:55:45 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0003\n",
      "19/03/08 06:55:45 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0003/\n",
      "19/03/08 06:55:45 INFO mapreduce.Job: Running job: job_1552022483956_0003\n",
      "19/03/08 06:56:01 INFO mapreduce.Job: Job job_1552022483956_0003 running in uber mode : false\n",
      "19/03/08 06:56:01 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 06:56:17 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000003/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:56:18 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000002/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:56:34 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000004/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:56:34 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000005/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:56:50 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000007/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:56:51 INFO mapreduce.Job: Task Id : attempt_1552022483956_0003_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0003/container_1552022483956_0003_01_000008/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:57:06 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 06:57:06 INFO mapreduce.Job: Job job_1552022483956_0003 failed with state FAILED due to: Task failed task_1552022483956_0003_m_000001\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 06:57:06 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=1\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=111850\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=111850\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=111850\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=114534400\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 06:57:06 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "NUM_REDUCERS=1\n",
    "\n",
    "hdfs dfs -rm -r -skipTrash ${OUT_DIR} > /dev/null\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    -D mapred.jab.name=\"wordCount\" \\\n",
    "    -D mapreduce.job.reduces=${NUM_REDUCERS} \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output wordOutput\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "packageJobJar: [/tmp/hadoop-unjar7733191181882496816/] [] /tmp/streamjob3936230658531330806.jar tmpDir=null\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "19/03/08 06:58:13 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:58:13 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 06:58:15 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 06:58:15 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 06:58:15 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 06:58:16 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0004\n",
      "19/03/08 06:58:16 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0004\n",
      "19/03/08 06:58:16 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0004/\n",
      "19/03/08 06:58:16 INFO mapreduce.Job: Running job: job_1552022483956_0004\n",
      "19/03/08 06:58:33 INFO mapreduce.Job: Job job_1552022483956_0004 running in uber mode : false\n",
      "19/03/08 06:58:33 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 06:58:49 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000003/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:58:49 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000002/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:59:06 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000004/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:59:06 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000005/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:59:23 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000006/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:59:24 INFO mapreduce.Job: Task Id : attempt_1552022483956_0004_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0004/container_1552022483956_0004_01_000007/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 06:59:40 INFO mapreduce.Job:  map 50% reduce 100%\n",
      "19/03/08 06:59:41 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 06:59:41 INFO mapreduce.Job: Job job_1552022483956_0004 failed with state FAILED due to: Task failed task_1552022483956_0004_m_000001\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 06:59:41 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=1\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=117268\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=117268\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=117268\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=120082432\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 06:59:41 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "NUM_REDUCERS=1\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    \n",
    "    -D mapreduce.job.reduces=${NUM_REDUCERS} \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output wordOutputRes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "packageJobJar: [/tmp/hadoop-unjar4796742709347739943/] [] /tmp/streamjob3523755287837207169.jar tmpDir=null\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "19/03/08 07:01:39 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 07:01:40 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 07:01:42 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 07:01:42 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 07:01:42 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0005\n",
      "19/03/08 07:01:43 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0005\n",
      "19/03/08 07:01:43 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0005/\n",
      "19/03/08 07:01:43 INFO mapreduce.Job: Running job: job_1552022483956_0005\n",
      "19/03/08 07:02:00 INFO mapreduce.Job: Job job_1552022483956_0005 running in uber mode : false\n",
      "19/03/08 07:02:00 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 07:02:16 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000002/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:02:16 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000003/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:02:32 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000004/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:02:33 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000005/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:02:48 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000007/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:02:49 INFO mapreduce.Job: Task Id : attempt_1552022483956_0005_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:449)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 9 more\n",
      "Caused by: java.lang.RuntimeException: Error in configuring object\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)\n",
      "\t... 14 more\n",
      "Caused by: java.lang.reflect.InvocationTargetException\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
      "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)\n",
      "\tat org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)\n",
      "\t... 17 more\n",
      "Caused by: java.lang.RuntimeException: configuration exception\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:221)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)\n",
      "\t... 22 more\n",
      "Caused by: java.io.IOException: Cannot run program \"/tmp/hadoop-root/nm-local-dir/usercache/jovyan/appcache/application_1552022483956_0005/container_1552022483956_0005_01_000008/./mapper.py\": error=2, No such file or directory\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:208)\n",
      "\t... 23 more\n",
      "Caused by: java.io.IOException: error=2, No such file or directory\n",
      "\tat java.lang.UNIXProcess.forkAndExec(Native Method)\n",
      "\tat java.lang.UNIXProcess.<init>(UNIXProcess.java:247)\n",
      "\tat java.lang.ProcessImpl.start(ProcessImpl.java:134)\n",
      "\tat java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)\n",
      "\t... 24 more\n",
      "\n",
      "19/03/08 07:03:06 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 07:03:07 INFO mapreduce.Job: Job job_1552022483956_0005 failed with state FAILED due to: Task failed task_1552022483956_0005_m_000000\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 07:03:07 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=1\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=115400\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=115400\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=115400\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=118169600\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 07:03:07 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output wordOutputResult"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "rm: `wordcount_reslt_1552033326239813': No such file or directory\n",
      "19/03/08 08:22:15 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 08:22:15 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032\n",
      "19/03/08 08:22:17 INFO mapred.FileInputFormat: Total input files to process : 1\n",
      "19/03/08 08:22:17 WARN hdfs.DataStreamer: Caught exception\n",
      "java.lang.InterruptedException\n",
      "\tat java.lang.Object.wait(Native Method)\n",
      "\tat java.lang.Thread.join(Thread.java:1252)\n",
      "\tat java.lang.Thread.join(Thread.java:1326)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:927)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:578)\n",
      "\tat org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:755)\n",
      "19/03/08 08:22:18 INFO mapreduce.JobSubmitter: number of splits:2\n",
      "19/03/08 08:22:18 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1552022483956_0008\n",
      "19/03/08 08:22:18 INFO impl.YarnClientImpl: Submitted application application_1552022483956_0008\n",
      "19/03/08 08:22:18 INFO mapreduce.Job: The url to track the job: http://23d861e5cf69:8088/proxy/application_1552022483956_0008/\n",
      "19/03/08 08:22:18 INFO mapreduce.Job: Running job: job_1552022483956_0008\n",
      "19/03/08 08:22:33 INFO mapreduce.Job: Job job_1552022483956_0008 running in uber mode : false\n",
      "19/03/08 08:22:33 INFO mapreduce.Job:  map 0% reduce 0%\n",
      "19/03/08 08:22:47 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000001_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:22:47 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000000_0, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:23:00 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000001_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:23:01 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000000_1, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:23:14 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000001_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:23:15 INFO mapreduce.Job: Task Id : attempt_1552022483956_0008_m_000000_2, Status : FAILED\n",
      "Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)\n",
      "\tat org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)\n",
      "\tat org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)\n",
      "\tat org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)\n",
      "\tat org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)\n",
      "\tat org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)\n",
      "\tat org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1807)\n",
      "\tat org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)\n",
      "\n",
      "19/03/08 08:23:28 INFO mapreduce.Job:  map 100% reduce 100%\n",
      "19/03/08 08:23:29 INFO mapreduce.Job: Job job_1552022483956_0008 failed with state FAILED due to: Task failed task_1552022483956_0008_m_000001\n",
      "Job failed as tasks failed. failedMaps:1 failedReduces:0\n",
      "\n",
      "19/03/08 08:23:30 INFO mapreduce.Job: Counters: 17\n",
      "\tJob Counters \n",
      "\t\tFailed map tasks=7\n",
      "\t\tKilled map tasks=1\n",
      "\t\tKilled reduce tasks=2\n",
      "\t\tLaunched map tasks=8\n",
      "\t\tOther local map tasks=6\n",
      "\t\tData-local map tasks=2\n",
      "\t\tTotal time spent by all maps in occupied slots (ms)=95105\n",
      "\t\tTotal time spent by all reduces in occupied slots (ms)=0\n",
      "\t\tTotal time spent by all map tasks (ms)=95105\n",
      "\t\tTotal time spent by all reduce tasks (ms)=0\n",
      "\t\tTotal vcore-milliseconds taken by all map tasks=95105\n",
      "\t\tTotal vcore-milliseconds taken by all reduce tasks=0\n",
      "\t\tTotal megabyte-milliseconds taken by all map tasks=97387520\n",
      "\t\tTotal megabyte-milliseconds taken by all reduce tasks=0\n",
      "\tMap-Reduce Framework\n",
      "\t\tCPU time spent (ms)=0\n",
      "\t\tPhysical memory (bytes) snapshot=0\n",
      "\t\tVirtual memory (bytes) snapshot=0\n",
      "19/03/08 08:23:30 ERROR streaming.StreamJob: Job not successful!\n",
      "Streaming Command Failed!\n",
      "cat: `wordcount_reslt_1552033326239813/part-00000': No such file or directory\n"
     ]
    }
   ],
   "source": [
    "%%bash\n",
    "\n",
    "OUT_DIR=\"wordcount_reslt_\"$(date +\"%s%6N\")\n",
    "NUM_REDUCERS=2\n",
    "\n",
    "hdfs dfs -rm -r -skipTrash ${OUT_DIR} > /dev/null\n",
    "\n",
    "yarn jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-streaming.jar \\\n",
    "    -D mapreduce.job.reduces=${NUM_REDUCERS} \\\n",
    "    -files mapper.py,reducer.py \\\n",
    "    -mapper \"mapper.py\" \\\n",
    "    -combiner \"reducer.py\" \\\n",
    "    -reducer \"reducer.py\" \\\n",
    "    -input word \\\n",
    "    -output ${OUT_DIR} > /dev/null\n",
    "\n",
    "hdfs dfs -cat ${OUT_DIR}/part-00000 | head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
